# Generated by Django 3.0.5 on 2023-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mktg_master',
            fields=[
                ('user_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='administrator', max_length=13)),
                ('user_name', models.CharField(default='a', max_length=40)),
                ('email_id', models.CharField(default=0, max_length=20)),
                ('phone_no', models.CharField(default=0, max_length=10)),
                ('password', models.CharField(default='12345678', max_length=20)),
            ],
        ),
    ]
