# Generated by Django 3.0.5 on 2023-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mktg_master',
            name='user_type',
            field=models.CharField(default='marketing', max_length=13),
        ),
    ]
