# Generated by Django 3.0.5 on 2023-05-21 07:44

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('marketing', '0005_auto_20230521_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mktg_master',
            options={'ordering': ['username'], 'verbose_name': 'Marketing User', 'verbose_name_plural': 'Marketing Users'},
        ),
        migrations.AlterModelManagers(
            name='mktg_master',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='marketing_users', related_query_name='marketing_user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='mktg_master',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='marketing_users', related_query_name='marketing_user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='mktg_master',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='mktg_master',
            name='phone_no',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AlterModelTable(
            name='mktg_master',
            table='mktg_master',
        ),
    ]
