# Generated by Django 3.0.5 on 2023-05-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20230521_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mktg_master',
            options={},
        ),
        migrations.AlterModelManagers(
            name='mktg_master',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='mktg_master',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='mktg_master',
            name='password',
            field=models.CharField(default='12345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='mktg_master',
            name='phone_no',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterModelTable(
            name='mktg_master',
            table=None,
        ),
    ]
