# Generated by Django 3.0.5 on 2023-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_customer_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_master',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer_master',
            name='pin',
            field=models.IntegerField(default=530032),
        ),
    ]
