# Generated by Django 3.0.5 on 2023-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_auto_20230607_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_master',
            name='city',
            field=models.CharField(default='vizag', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer_master',
            name='email_id',
            field=models.CharField(default='abc@gmail.com', max_length=30),
        ),
    ]
