# Generated by Django 3.0.5 on 2023-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_auto_20230607_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='yard',
            fields=[
                ('yard_no', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
