# Generated by Django 3.0.5 on 2023-06-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_sale_order_yard_despatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yard',
            new_name='yard_master',
        ),
    ]
