# Generated by Django 3.0.5 on 2023-06-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_auto_20230618_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard_despatch',
            name='yard_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.yard_master'),
        ),
    ]
