# Generated by Django 3.0.5 on 2023-06-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_product_master'),
        ('marketing', '0017_auto_20230618_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yard_despatch',
            new_name='yard_despatchs',
        ),
        migrations.RenameModel(
            old_name='yard_receipts',
            new_name='yardreceipts',
        ),
    ]
