# Generated by Django 3.0.5 on 2023-06-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_transport_master'),
        ('marketing', '0019_auto_20230621_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard_despatchs',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.transport_master'),
        ),
        migrations.AlterField(
            model_name='yardreceipts',
            name='transport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.transport_master'),
        ),
    ]
