# Generated by Django 3.0.5 on 2023-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_auto_20230623_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard_despatchs',
            name='transport_type',
            field=models.CharField(default='truck', max_length=10),
        ),
        migrations.AlterField(
            model_name='yardreceipts',
            name='transport_type',
            field=models.CharField(default='truck', max_length=10),
        ),
    ]
