# Generated by Django 3.0.5 on 2023-06-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_master',
            old_name='user_id',
            new_name='username',
        ),
    ]
