# Generated by Django 3.0.5 on 2023-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20230607_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_master',
            fields=[
                ('product_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('product_desc', models.CharField(default='steel', max_length=40)),
                ('stock_in_tons', models.IntegerField(default=0)),
                ('location', models.CharField(default='furnace', max_length=20)),
                ('product_grade', models.CharField(default='a', max_length=10)),
            ],
        ),
    ]
